server:
  port: 7030 #运行端口号

spring:
  application:
    name: dmall-framework-config-server #服务名称

  cloud:
    config:
      server:
        git: #配置存储配置信息的Git仓库
          uri: https://github.com/yuhangtdm/dmall-config
          username: yuhangtdm
          password: yhmm5201314
          clone-on-start: true #开启启动时直接从git获取配置
          search-paths: dmall-framework-dashboard
  security: #配置用户名和密码
    user:
      name: dmall
      password: admin123456

#  rabbitmq: #rabbitmq相关配置
#    host: www.os01.com
#    port: 5673
#    username: guest
#    password: guest

eureka:
  client:
    register-with-eureka: true #注册到Eureka的注册中心
    fetch-registry: true #获取注册实例列表
    service-url:
      defaultZone: http://dmall:admin123456@www.dmall.com:7000/eureka/,http://dmall:admin123456@dmall1:7001/eureka/ #配置注册中心地址
    healthcheck:
      enabled: true #开启健康检查
  instance:
    prefer-ip-address: true #采用IP注册
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port} #定义实例ID格式
    lease-renewal-interval-in-seconds: 30 #定义服务多久去注册中心续约
    lease-expiration-duration-in-seconds: 90 #定义服务多久不去续约认为服务失效

#management:
#  endpoints: #暴露bus刷新配置的端点
#    web:
#      exposure:
#        include: 'bus-refresh'

swagger:
  enabled: false